[tox]
envlist = test, doc

[testenv]
basepython = python3
passenv = http_proxy, https_proxy
deps =
    -rrequirements.dev.txt
changedir = {envtmpdir}


[testenv:test]
commands =
    {envpython} -c "import pyszn; print(pyszn.__file__)"
    flake8 {toxinidir}
    py.test -s \
        --junitxml=tests.xml \
        --cov=pyszn \
        --cov-report xml \
        --cov-report html \
        --cov-report term \
        {posargs} \
        {toxinidir}/test \
        {envsitepackagesdir}/pyszn


[testenv:doc]
allowlist_externals =
    dot
commands =
    sphinx-build -W -b html -d doctrees {toxinidir}/doc/ html


[testenv:release]
# Edit version:
#
#    nano lib/pyszn/__init__.py
#
# Update changelog in README.rst:
#
#    nano README.rst
#
# Commit, tag:
#
#    git commit -a
#        Bumping version number to x.y.z.
#    git tag x.y.z
#
# Push new revision and tag:
#
#    git push
#    git push origin x.y.z
#
# Release package:
#
#    tox -e release
#
skip_install = True
deps =
    twine
commands =
    uv build {toxinidir}
    # Using twine check as uv doesn't have an equivalent command
    # https://github.com/astral-sh/uv/issues/8641
    # And yes, I had a release ready that failed to upload because of this :D
    twine check {toxinidir}/dist/ninjecto*
    {envpython} -c "print((\
        'Packages ready. When ready, execute:\n'\
        'uv publish --token ${PYPI_HPE_TOKEN} {toxinidir}/dist/*'\
    ))"


[flake8]
exclude = .git,.tox,.cache,__pycache__,build,*.egg-info


[pytest]
